import "./globals.css";

import { Sora } from "next/font/google";

import Header from "./components/Header";
import Footer from "./components/Footer";
import Providers from "./components/Provider";
import { Toaster } from "react-hot-toast";
import { Metadata } from "next";

// const inter = Inter({ subsets: ["latin"] });
const sora = Sora({ subsets: ["latin"] });

// export const metadata = {
//   title: "Hacktathon Dine Market",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  title: {
    default: "Dine Market",
    template: "%s",
  },
  description: "Dine Market",
  openGraph: {
    title: "Hackathon Dine Marke",
    description: "Vintage-Minimalistic-Portfolio",
    url: "https://hackathon1-omega.vercel.app/",
    siteName: "Dine Market",
    locale: "en_US",
    type: "website",
    images: "/opengraph-image.png",
  },
  twitter: {
    card: "summary_large_image",
    title: "Dine Market",
    description: "Dine Market",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Providers>
          <Header />
          {children}
          <Toaster position="top-right" reverseOrder={false} />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
