"use client";
import "./globals.css";
// import { Inter } from "next/font/google";
import { Sora } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Providers from "./components/Provider";
import { store } from "@/app/store/store";
import { Provider } from "react-redux";
import { Toaster } from "react-hot-toast";

// const inter = Inter({ subsets: ["latin"] });
const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={sora.className}>
          <Header />
          {children}
          <Toaster position="top-right" reverseOrder={false} />
          <Footer />
        </body>
      </html>
    </Provider>
  );
}
