"use client";
import "./globals.css";
// import { Inter } from "next/font/google";
import { Sora } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Providers from "./components/Provider";
import { store } from "@/app/store/store";
import { Provider } from "react-redux";

// const inter = Inter({ subsets: ["latin"] });
const sora = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Provider store={store}>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
